### ISSUE TITLE
need update on command 

### ISSUE THREAD

**Issue by armagadon159753** [CzechPMDevs/1vs1#1]
10.09 16:42:08 [Server] Server thread/INFO Enabling 1vs1 v1.0.0 [DEV]
10.09 16:42:08 [Server] INFO Fatal error: Declaration of OneVsOne\Command\OneVsOneCommand::execute(pocketmine\command\CommandSender $sender, string $commandLabel, array $args) must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args) in /plugins/1VSS1/src/OneVsOne/Command/OneVsOneCommand.php on line 19

**Comment by GamakCZ** [comment]
This plugin is under development and is for API 3.0.0-ALPHA7, if you want
test it, you can download newtest version of PocketMine on poggit.

Dne 10. 9. 2017 16:43 napsal uživatel "FakeDev.apk" <
notifications@github.com>:

**Comment by armagadon159753** [comment]
If you want i can make fork and add dôme change for full pmmp support

**Comment by GamakCZ** [comment]
It is full compatible :/



https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/command/PluginCommand.php#L48


https://github.com/CzechPMDevs/1vs1/blob/master/1vs1/src/OneVsOne/Command/OneVsOneCommand.php#L42

**Comment by GamakCZ** [comment]
GenisysPro support will be added soon.

**Comment by armagadon159753** [comment]
OK maybe its me because i m 32bit i do use old pmmp src
